//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int vehicleID { get; set; }
        public Nullable<decimal> vehiclePrice { get; set; }
        public Nullable<int> vehicleNumberPlate { get; set; }
        public string vehicleBrand { get; set; }
        public string vehicleModel { get; set; }
        public string vehicleYear { get; set; }
        public string vehicleMotor { get; set; }
        public string vehiclePackage { get; set; }
        public string vehicleColor { get; set; }
        public string vehicleGear { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> branchID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
